docker_archs:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64
docker_arch: "{{ docker_archs[ansible_facts.architecture] }}"
docker_distr_release: "{{ ansible_facts.distribution_release }}"
docker_key_path: "/etc/apt/keyrings/docker.asc"
