- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl

- name: Download docker repo key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ docker_key_path }}"
    mode: "0644"

- name: Add Docker APT repository
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ docker_arch }} signed-by={{ docker_key_path }}] https://download.docker.com/linux/ubuntu {{ docker_distr_release }} stable"
    state: present
    update_cache: true

- name: Install docker
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add users to the docker-sudo group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['SUDO_USER'] }}"
    append: true
    groups:
      - docker
